version: '3.8'

services:
  mimoto-service:
    container_name: 'Mimoto-Service'
    image: 'vijaykumar151096/mimoto:auth'
    user: root
    ports:
      - 8088:8088
      - 8099:8099
      - 8089:80  # Map port 80 in the container to 8089 on the host
    environment:
      - artifactory_url_env=http://artifactory-server:8080/
      - container_user=mosip
      - active_profile_env=default
      - SPRING_CONFIG_NAME=mimoto
      - SPRING_CONFIG_LOCATION=/home/mosip/
    volumes:
      - ./docker-compose/config/mimoto-default.properties:/home/mosip/mimoto-default.properties
      - ./docker-compose/config/mimoto-issuers-config.json:/home/mosip/mimoto-issuers-config.json
      - ./docker-compose/config/oidckeystore.p12:/home/mosip/certs/oidckeystore.p12
      - ./docker-compose/loader_path/:/home/mosip/additional_jars/

